// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UBSFlow.Infraestrutura.Persistencia;

#nullable disable

namespace UBSFlow.Infraestrutura.Persistencia.Migrations
{
    [DbContext(typeof(UbsFlowDbContext))]
    [Migration("20260712183312_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UBSFlow.Dominio.Agenda.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Fim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionalId", "Inicio", "Fim");

                    b.ToTable("agendamentos", (string)null);
                });

            modelBuilder.Entity("UBSFlow.Dominio.Atendimentos.Atendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CheckInId")
                        .HasColumnType("uuid");

                    b.Property<string>("Conduta")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Encaminhamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("FinalizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HipoteseDiagnostica")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("IniciadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Prescricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Queixa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CheckInId")
                        .IsUnique();

                    b.ToTable("atendimentos", (string)null);
                });

            modelBuilder.Entity("UBSFlow.Dominio.Auditoria.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RegistradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("RegistradoEm");

                    b.ToTable("logs_auditoria", (string)null);
                });

            modelBuilder.Entity("UBSFlow.Dominio.Fila.CheckInAtendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgendamentoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RealizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId")
                        .IsUnique();

                    b.ToTable("check_ins_atendimento", (string)null);
                });

            modelBuilder.Entity("UBSFlow.Dominio.Pacientes.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cns")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("pacientes", (string)null);
                });

            modelBuilder.Entity("UBSFlow.Dominio.Profissionais.Profissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("RegistroProfissional")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("profissionais", (string)null);
                });

            modelBuilder.Entity("UBSFlow.Dominio.Triagens.Triagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CheckInId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassificacaoRisco")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FrequenciaCardiaca")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<int>("PressaoDiastolica")
                        .HasColumnType("integer");

                    b.Property<int>("PressaoSistolica")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RealizadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Temperatura")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.HasKey("Id");

                    b.HasIndex("CheckInId")
                        .IsUnique();

                    b.ToTable("triagens", (string)null);
                });

            modelBuilder.Entity("UBSFlow.Dominio.Profissionais.Profissional", b =>
                {
                    b.OwnsMany("UBSFlow.Dominio.Profissionais.DisponibilidadeSemanal", "Disponibilidades", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("DiaSemana")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<TimeOnly>("HoraFim")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly>("HoraInicio")
                                .HasColumnType("time without time zone");

                            b1.Property<Guid>("ProfissionalId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ProfissionalId");

                            b1.ToTable("profissionais_disponibilidades", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProfissionalId");
                        });

                    b.Navigation("Disponibilidades");
                });
#pragma warning restore 612, 618
        }
    }
}
